# Generated by Django 3.2.13 on 2022-04-29 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 10, 38, 44, 950282)),
        ),
    ]
