# Generated by Django 3.2.13 on 2022-05-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20220508_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('kind', models.CharField(choices=[('dish', 'Dish'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='dish', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_offer', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('is_daily', models.BooleanField(default=False)),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('items', models.ManyToManyField(to='management.Item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
