# Generated by Django 3.2.13 on 2022-05-23 08:57

import datetime
from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20220510_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[management.models.validate_date]),
        ),
    ]
