# Generated by Django 3.2.13 on 2022-06-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['kind']},
        ),
    ]
